Revert "Try dropping pyyaml dep from orchid-mac build"
This reverts commit 9a5619de6054d4835f586c273ab4a07ddc26c0f9.

Without these lines, the orchid-mac build fails with:

cd ./vpn/./duktape && rm -rf prep/nondebug && make prep/nondebug
flex -t --header-file=out-mac/./vpn/wsk/wireshark/wiretap/ascend_scanner_lex.h vpn/wsk/wireshark/wiretap/ascend_scanner.l >out-mac/./vpn/wsk/wireshark/wiretap/ascend_scanner.c
flex -t --header-file=out-mac/./vpn/wsk/wireshark/wiretap/candump_scanner_lex.h vpn/wsk/wireshark/wiretap/candump_scanner.l >out-mac/./vpn/wsk/wireshark/wiretap/candump_scanner.c
/usr/local/bin/python2 tools/configure.py --output-directory ./prep/nondebug --source-directory src-input --config-metadata config --option-file util/makeduk_base.yaml --line-directives
Traceback (most recent call last):
File "tools/configure.py", line 29, in <module>
    import yaml
ImportError: No module named yaml
make[1]: *** [prep/nondebug] Error 1
make: *** [vpn/./duktape/prep/nondebug/duktape.h] Error 2
make: *** Waiting for unfinished jobs....
 ##[error]Process completed with exit code 2.